services:
  - docker
before_install:
  - echo "Enter before install stage.."
  - echo "Start creating an image with dockerfile.."
  - docker build -t kde/docker-react-app -f Dockerfile.dev .
script:
  - echo "Run test"
  - docker run -e CI=true kde/docker-react-app npm run test -- --coverage
after_success:
  - echo "Test success"